environment_path: ./holochain_backend_data
network:
  transport_pool:
    - type: webrtc
      signal_url: "wss://signal.holo.host"
  bootstrap_service: "https://bootstrap.holo.host/"
  tuning_params:
    gossip_strategy: sharded-gossip
    gossip_loop_iteration_delay_ms: "1000"
    gossip_outbound_target_mbps: "100"
    gossip_inbound_target_mbps: "100"
    gossip_historic_outbound_target_mbps: "100"
    gossip_historic_inbound_target_mbps: "100"
    gossip_burst_ratio: "100"
    gossip_peer_on_success_next_gossip_delay_ms: "60000"
    gossip_peer_on_error_next_gossip_delay_ms: "300000"
    gossip_agent_info_update_interval_ms: "300000"
    gossip_round_timeout_ms: "60000"
    gossip_redundancy_target: "100"
    gossip_max_batch_size: "1000000"
    gossip_dynamic_arcs: "true"
    gossip_arc_clamping: none
    default_rpc_single_timeout_ms: "60000"
    default_rpc_multi_remote_agent_count: "3"
    default_rpc_multi_remote_request_grace_ms: "3000"
    agent_info_expires_after_ms: "1200000"
    tls_in_mem_session_storage: "512"
    proxy_keepalive_ms: "120000"
    proxy_to_expire_ms: "300000"
    concurrent_limit_per_thread: "4096"
    tx2_quic_max_idle_timeout_ms: "60000"
    tx2_pool_max_connection_count: "4096"
    tx2_channel_count_per_connection: "2"
    tx2_implicit_timeout_ms: "60000"
    tx2_initial_connect_retry_delay_ms: "200"
    tx5_max_send_bytes: "16777216"
    tx5_max_recv_bytes: "16777216"
    tx5_max_conn_count: "255"
    tx5_max_conn_init_s: "60"
    tx5_ban_time_s: "10"
    danger_tls_keylog: no_keylog
    danger_gossip_recent_threshold_secs: "900"
    disable_publish: "false"
    disable_recent_gossip: "false"
    disable_historical_gossip: "false"
    bootstrap_check_delay_backoff_multiplier: "2"
  network_type: quic_bootstrap
admin_interfaces:
  - driver:
      type: websocket
      port: 1234