/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CreateAudit: typeof import('./src/components/CreateAudit.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    NormpointSelection: typeof import('./src/components/NormpointSelection.vue')['default']
    NormSelection: typeof import('./src/components/NormSelection.vue')['default']
  }
}
